// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scan} from '../models';

export function CancelLogin():Promise<void>;

export function Chain(arg1:scan.ChainRequest):Promise<string>;

export function Clear():Promise<void>;

export function DefaultProfile():Promise<scan.Profile>;

export function ExtractProfile(arg1:string):Promise<scan.Profile>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function SaveText(arg1:string,arg2:string):Promise<boolean>;

export function Start(arg1:scan.Request):Promise<void>;

export function Status():Promise<scan.Status>;

export function Stop():Promise<void>;

export function Version():Promise<string>;
