// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLogin() {
  return window['go']['main']['App']['CancelLogin']();
}

export function Chain(arg1) {
  return window['go']['main']['App']['Chain'](arg1);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function DefaultProfile() {
  return window['go']['main']['App']['DefaultProfile']();
}

export function ExtractProfile(arg1) {
  return window['go']['main']['App']['ExtractProfile'](arg1);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
